[package]
name = "pulsar-core"
version = "0.1.0"
edition = "2024"

[dependencies]
dasp = "0.11.0"
fundsp = "0.20.0"
parking_lot = "0.12.4"
serde = "1.0.225"
serde_json = "1.0.145"
thiserror = "2.0.16"
wide = "0.7.33"
